### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by luizjr8** [luizjr8/tarefadecasa#1]
v1.
——

- [ ] Timer para tarefas (com barra de progresso svg)
- [ ] Área de Escrita Cursiva
- [ ] Área de Imagem da Internet
- [ ] Css para não desligar a tela (tentar isso via meta ou via gpu)

v2.
——

- [ ] Área de Operações matemáticas (com grid para centena, dezena, unidade)
- [ ] Área para vídeos (youtube ou url)

v3.
—

- [ ] Video-conferência
